name: Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/_gradle-build.yml
    with:
      job_name: Shared and web tests
      runner: ubuntu-24.04
      command: ./gradlew --stacktrace :shared:desktopTest :shared:wasmJsBrowserTest
