name: Web

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_gradle-build.yml
    with:
      job_name: Web distribution
      runner: ubuntu-24.04
      command: ./gradlew --stacktrace :app:wasmJsBrowserDistribution
      artifact_name: molliecaster-web
      artifact_path: app/build/dist/wasmJs/productionExecutable/
